version: '2'

services:
  selenium:
    image: selenium/standalone-chrome-debug:3.14.0
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm
    ports:
     - "4444:4444"
     - "5900:5900"
    shm_size: '2gb'
networks:
  default:
    external:
      name: env_default
